### ISSUE TITLE
库无法正常使用

### ISSUE THREAD

**Issue by Jack253-png** [CarmJos/GithubReleases4J#1]
无法正常查询github的release版本

直接调用listRelease函数时

应该会列举出来所有release版本

![image](https://user-images.githubusercontent.com/83895170/175816253-31a99952-2523-4391-b25b-ddec72adf19f.png)

win10 1903
openjdk jetbrains runtime 11
gradle 7.3.3

而我自己访问api是正常的

**Comment by Jack253-png** [comment]
![image](https://user-images.githubusercontent.com/83895170/175816389-7c5b64ac-62ac-4911-ab03-f309132ddf77.png)
正常访问时

**Comment by Jack253-png** [comment]
即使信任所有证书还是这样

**Comment by Jack253-png** [comment]
![image](https://user-images.githubusercontent.com/83895170/175817883-a2286630-b68b-4cab-bc49-2218c51f97e1.png)
包括自己写api也是正常的

**Comment by CarmJos** [comment]
![Uploading image.png…]()

**Comment by CarmJos** [comment]
经测，功能正常，请检查自己的代码和网络。

**Comment by CarmJos** [comment]
![image](https://user-images.githubusercontent.com/36306882/175820769-c216e22f-f672-46ba-8752-22ec659c2953.png)

**Comment by Jack253-png** [comment]
这似乎是我加速器的问题，但是我自己写的没问题，那么还是我自己写吧，因为自己写的能修改，你的库用的是maven，没有办法修改，看到报错。还是谢谢你，告诉我了github api的路径和用法



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月26日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CarmJos/GithubReleases4J] 库无法正常使用 (Issue #1) |

**Comment by Jack253-png** [comment]
果然，是证书的问题

**Comment by Jack253-png** [comment]
希望你以后的版本里多加一个信任所证书

**Comment by Jack253-png** [comment]
private static void trustAllHosts() {
        final String TAG = "trustAllHosts";
        TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new java.security.cert.X509Certificate[] {};
            }
            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
//                Log.i(TAG, "checkClientTrusted");
            }
            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
//                Log.i(TAG, "checkServerTrusted");
            }
        } };
        // Install the all-trusting trust manager
        try {
            SSLContext sc = SSLContext.getInstance("TLS");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by Jack253-png** [comment]
这样就可以了
